### ISSUE TITLE
Missing auto-complete-clang-async.el ?

### ISSUE THREAD

**Issue by CodingTink** [psycofdj/xtdmacs#7]
Hi :)

Upon loading a cpp file (or whatever triggers ac-clang-async-mode):
_xtdmacs-loader-load-minor-modes: Cannot open load file: No such file or directory, vendor/auto-complete-clang-async.el_

From xtdmacs-vendor.el:
(autoload 'ac-clang-async-mode "vendor/auto-complete-clang-async.el")

Indeed, the file is not there :/
How should I fix this ?

**Comment by psycofdj** [comment]
Hi @CodingTink 
Release [v0.5](https://github.com/psycofdj/xtdmacs/releases/tag/v0.5) integrates [irony](https://github.com/Sarcasm/irony-mode) which sould solve your issue.

**Comment by CodingTink** [comment]
Thanks 👍
